### ISSUE TITLE
Pagination in 1.1.0b5

### ISSUE THREAD

**Issue by andoriyu** [couchrest/couchrest_model#81]
Strange thing. I was using Item.by_sku.paginate to paginate my catalog, but after updating to 1.1.0b5 i got this error:

```
ruby-1.9.2-p180 :004 > Item.by_sku.paginate
NoMethodError: undefined method `paginate' for #<Array:0x00000104b8eb88>

ruby-1.9.2-p180 :012 > Article.paginate(:page => 1, :per_page => 2, :design_doc => 'Article', :view_name => 'by_date')
NoMethodError: undefined method `[]' for nil:NilClass
from /Users/andoriyu/.rvm/gems/ruby-1.9.2-p180@ngein/bundler/gems/couchrest_model-fcd9e2ba8e0f/lib/couchrest/model/persistence.rb:113:in `build_from_database'
```
